tensorboard:
  _target_ : pytorch_lightning.loggers.TensorBoardLogger
  save_dir : ${original_work_dir}/tb_logs
  name : ${name}
  version : ${label}
csv:
  _target_ : pytorch_lightning.loggers.CSVLogger
  save_dir : ${original_work_dir}/csv_logs
  name : ${name}
  version : ${label}
