name : 'l1_real_l1lr'
sim_losses: null
real_losses :
  - _target_ : torchsisr.loss_helper.PixelLossWrapper
    loss:
      _target_ : torchsisr.loss.PerBandWrapper
      loss:
        _target_ : torch.nn.L1Loss
    name : 'l1'
    bands : ['B2', 'B3', 'B4', 'B8']
  - _target_ : torchsisr.loss_helper.PixelLossWrapper
    loss:
      _target_ : torchsisr.loss.PerBandWrapper
      loss:
        _target_ : torch.nn.L1Loss
    name : 'l1'
    bands : ['B5', 'B6', 'B7', 'B8A']
    weight : 1.0
  - _target_ : torchsisr.loss_helper.AgainstHRInputPixelLossWrapper
    loss:
      _target_: torchsisr.loss.LRFidelity
      loss:
        _target_ : torch.nn.SmoothL1Loss
      factor : 2.0
      mtf : 0.4
    name: 'lr_l1'
    bands: ['B2', 'B3', 'B4', 'B8']
  - _target_ : torchsisr.loss_helper.AgainstLRInputPixelLossWrapper
    loss:
      _target_: torchsisr.loss.LRFidelity
      loss:
        _target_ : torch.nn.SmoothL1Loss
      factor : 4.0
      mtf : 0.4
    name: 'lr_l1'
    bands: ['B5', 'B6', 'B7', 'B8A']

wald_losses:
  - _target_ : torchsisr.loss_helper.PixelLossWrapper
    loss:
      _target_ : torchsisr.loss.PerBandWrapper
      loss:
        _target_ : torch.nn.L1Loss
    name : 'l1'
    bands : ['B11', 'B12']
    weight : 1.0
