sim_losses: null
real_losses :
  - _target_ : torchsisr.loss_helper.AgainstHRInputPixelLossWrapper
    loss:
      _target_: torchsisr.loss.LRFidelity
      loss:
        _target_ : torch.nn.MSELoss
      factor : ${model.generator.upsampling_factor}
      mtf : 0.4
    name: 'lr_l2'
    bands : ${training_module.bands}
    weight : 0.1
  - _target_: torchsisr.loss_helper.PixelLossWrapper
    loss:
      _target_ : torchsisr.loss.PerBandWrapper
      loss:
        _target_ : piq.LPIPS
      dimension_4_needed: True
    name : 'lpips'
    bands : ${training_module.bands}
wald_losses: null
