_target_: pytorch_lightning.Trainer
accelerator: 'gpu'
devices: 1
min_epochs: 1
max_epochs: 10
log_every_n_steps : 10
val_check_interval : 162
num_sanity_val_steps : 0
precision : '16-mixed'
deterministic: false
#profiler : 'pytorch'
#max_steps : 10
